on:
  pull_request:
  push:
    branches:
      - main

name: analyze

jobs:
  build:
    name: Lint flutter code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - name: Analyze Dart
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./