on: pull_request

name: preview-pr
permissions:
  pull-requests: write

jobs:
  main:
    name: preview pr web build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'
          channel: 'stable'
      - name: flutter version
        run: flutter --version
      - name: flutter pub get
        run: flutter pub get
      - name: flutter build web
        run: flutter build web --no-tree-shake-icons --base-href "/${{ github.event.pull_request.number }}/"
      - name: upload to s3
        id: s3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.S3_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_KEY}}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          endpoint: ${{ env.S3_ENDPOINT }}
          source_dir: build/web
          destination_dir: ${{ github.event.pull_request.number }}
      - name: find first comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: web preview
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👋 Hi, I have prepared a preview of this PR with web build
            [🌐 Preview \#${{ github.event.pull_request.number }}](${{ env.S3_ENDPOINT }}/${{ github.event.pull_request.number }})
          edit-mode: replace
