on:
  push:
    branches:
      - main

name: release
permissions:
  contents: read

jobs:
  calc-release-version:
    name: calc-release-version
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # safety github token credential
          persist-credentials: false
          fetch-depth: 0
      - name: override releaserc config
        run: cat .releaserc-pubspec > .releaserc
      - name: calculate release version
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @64mb/semantic-release-flutter-plugin
            conventional-changelog
        env:
          # only for read
          GITHUB_TOKEN: ${{ secrets.CI_RELEASE_TOKEN }}
      - name: version
        run: cat pubspec.yaml | grep version
      - name: upload pubspec with new version
        uses: actions/upload-artifact@v3
        with:
          name: pubspec
          path: pubspec.yaml
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    needs: calc-release-version
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: download release pubspec
        uses: actions/download-artifact@v3
        with:
          name: pubspec
      - name: version
        run: cat pubspec.yaml | grep version
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'
          channel: 'stable'
      - name: apt install build deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip ninja-build libgtk-3-dev
      - name: flutter enable linux desktop target
        run: flutter config --enable-linux-desktop
      - name: flutter build linux
        run: flutter build linux
      - name: zip build linux
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: linux-x64.zip
          directory: build/linux/x64/release/bundle
      - name: upload linux build artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: build/linux/x64/release/bundle/linux-x64.zip
  build-windows:
    name: build-windows
    runs-on: windows-latest
    needs: calc-release-version
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: download release pubspec
        uses: actions/download-artifact@v3
        with:
          name: pubspec
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'
          channel: 'stable'
      - name: flutter enable windows desktop target
        run: flutter config --enable-windows-desktop
      - name: flutter build windows
        run: flutter build windows
      - name: zip build windows
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: windows-x64.zip
          directory: build/windows/runner/Release
      - name: upload windows build artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-x64
          path: build/windows/runner/Release/windows-x64.zip
  github-release:
    name: github-release
    runs-on: ubuntu-latest
    needs: [calc-release-version, build-linux, build-windows]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # safety github token credential
          persist-credentials: false
          fetch-depth: 0
      - name: download release pubspec
        uses: actions/download-artifact@v3
        with:
          name: pubspec
      - name: version
        run: cat pubspec.yaml | grep version
      - name: download linux build artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-x64
      - name: download windows build artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-x64
      - name: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @64mb/semantic-release-flutter-plugin
            conventional-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.CI_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: 64mb.ru
          GIT_AUTHOR_EMAIL: robot@64mb.ru
          GIT_COMMITTER_NAME: 64mb.ru
          GIT_COMMITTER_EMAIL: robot@64mb.ru
