on:
  push:
    branches:
      - release

name: release
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  bump-version:
    name: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # safety github token credential
          persist-credentials: false
          fetch-depth: 0
      - name: bump release version
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @64mb/semantic-release-flutter-plugin
            conventional-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.CI_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: 64mb
          GIT_AUTHOR_EMAIL: robot@64mb.ru
          GIT_COMMITTER_NAME: 64mb
          GIT_COMMITTER_EMAIL: robot@64mb.ru
  build-linux:
    name: release-linux
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # safety github token credential
          persist-credentials: false
          fetch-depth: 0
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'
          channel: 'stable'
      - name: apt install build deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip ninja-build libgtk-3-dev
      - name: flutter enable linux desktop target
        run: flutter config --enable-linux-desktop
      - name: flutter build linux
        run: flutter build linux
      - name: zip build linux
        run: cd build/linux/x64/release/bundle && zip -r pilot-s3-linux-x64.zip .
      - name: upload linux build artifact
        uses: actions/upload-artifact@v3
        with:
          name: pilot-s3-linux-x64
          path: build/linux/x64/release/bundle/pilot-s3-linux-x64.zip
  github-release:
    name: github-release
    runs-on: ubuntu-latest
    # needs: [build-linux, build-windows]
    needs: [bump-version, build-linux]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # safety github token credential
          persist-credentials: false
          fetch-depth: 0
      - run: git checkout HEAD^
      - name: download linux build artifact
        uses: actions/download-artifact@v3
        with:
          name: pilot-s3-linux-x64
      - name: override release config
        run: cat .releaserc-github > .releaserc
      - name: release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
